### ISSUE TITLE
Setting useNewUrlParser to true does not allow the server to start

### ISSUE THREAD

**Issue by RichardMoj** [SirMaximilian/CSCI_150FA19_Sensor_Network#6]
mongoose connect option, useNewUrlParser is currently set to false. On initial start up of the server, a deprecation warning is given suggesting to set it to True. However, upon setting it to true, the server can no longer start.

**Comment by SirMaximilian** [comment]
I think this was because we were using an old version of MongoDB. We are now updated to 4.2
