### ISSUE TITLE
Data collection fails if "Value" is type "int"

### ISSUE THREAD

**Issue by JoshKonior** [SirMaximilian/CSCI_150FA19_Sensor_Network#8]
It doesn't happen very often, but on the off chance there is no decimal value for "Value" from a sensor, it creates an int. The main.dart code currently cannot distinguish between double and int values and breaks if it sees such a type.
Possible Fixes: 
-Append .0 to int values from server side
-Fix how the data is collected on main.dart side
![ints break code](https://user-images.githubusercontent.com/54963362/69497450-0deef680-0e92-11ea-94c9-df34af6a84e7.PNG)

**Comment by SirMaximilian** [comment]
I don't think this is a server issue. you can simply cast the data as a double or float on the mobile end

**Comment by JoshKonior** [comment]
Issue Resolved by casting the data to type double upon collection.
